# Generated by Django 3.1.5 on 2021-01-11 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_img', models.ImageField(blank=True, null=True, upload_to='projects-images/')),
                ('game_name', models.CharField(blank=True, max_length=100, null=True)),
                ('game_type', models.CharField(blank=True, choices=[('indoor', 'indoor games'), ('outdoor', 'outdoor games')], max_length=100, null=True)),
                ('game_rules', models.TextField(blank=True, null=True)),
                ('game_price', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kitchen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_img', models.ImageField(blank=True, null=True, upload_to='projects-images/')),
                ('item_name', models.CharField(blank=True, max_length=100, null=True)),
                ('item_type', models.CharField(blank=True, choices=[('drinks', 'drinks'), ('snacks', 'snacks'), ('chats', 'chats'), ('others', 'others')], max_length=100, null=True)),
                ('item_description', models.TextField(blank=True, null=True)),
                ('item_price', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_phone', models.IntegerField(blank=True, null=True)),
                ('user_info', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameBooked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_time', models.CharField(blank=True, max_length=100, null=True)),
                ('total_game_price', models.IntegerField(blank=True, null=True)),
                ('game_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gamer_zone.game')),
                ('user_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FoodBooked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_quantity', models.CharField(blank=True, max_length=100, null=True)),
                ('total_item_price', models.IntegerField(blank=True, null=True)),
                ('item_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gamer_zone.kitchen')),
                ('user_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FinalCheckout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_bill_status', models.BooleanField(default=False)),
                ('total_bill_amount', models.IntegerField(blank=True, null=True)),
                ('user_game_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gamer_zone.gamebooked')),
                ('user_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_item_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gamer_zone.foodbooked')),
            ],
        ),
    ]
