# Generated by Django 3.1.5 on 2021-01-21 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamer_zone', '0002_auto_20210122_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.CharField(blank=True, choices=[('outdoor', 'outdoor games'), ('indoor', 'indoor games')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gamebooked',
            name='game_time_start',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='item_type',
            field=models.CharField(blank=True, choices=[('chats', 'chats'), ('others', 'others'), ('drinks', 'drinks'), ('snacks', 'snacks')], max_length=100, null=True),
        ),
    ]
